djangogirls/blog/urls.py
from django.conf.urls import url
from . import views

# {} <- 이거 아닙니다
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
]

djangogirls/djangogirls/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from blog import views as blog_views
# from djangogirls import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^video/', include('video.urls', namespace='video')),

]

djangogirls/video/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^search/$', views.search, name='search'),
    url(r'^bookmark/add/$', views.bookmark_add, name='bookmark_add'),
    url(r'^bookmark/list/$', views.bookmark_list, name='bookmark_list'),
    url(r'^bookmark/(?P<pk>\d+)/$', views.bookmark_detail, name='bookmark_detail'),
    url(r'^bookmark/delete/(?P<pk>\d+)/$', views.bookmark_delete, name='bookmark_delete'),

]

djangogirls/video/models.py
import datetime
from django.db import models


class Video(models.Model):
    kind = models.CharField(max_length=100)
    youtube_id = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    published_date = models.DateTimeField(blank=True, null=True, default=datetime.datetime.now())
    thumbnail = models.URLField(blank=True)

    def __str__(self):
        return self.title

djangogirls/video/views/bookmark.py
from django.contrib import messages
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from video.models import Video

__all__ = ['bookmark_list', 'bookmark_add', 'bookmark_detail', 'bookmark_delete']


def bookmark_add(request):
    path = request.POST.get('path')
    try:
        kind = request.POST['kind']
        youtube_id = request.POST['youtube_id']
        title = request.POST['title']
        description = request.POST['description']
        published_date = request.POST['published_date']
        thumbnail = request.POST['thumbnail']

        Video.objects.create(
            kind=kind,
            youtube_id=youtube_id,
            title=title,
            description=description,
            published_date=published_date,
            thumbnail=thumbnail,
        )
        msg = "success"
    except Exception as e:
        msg = 'nope %s'%e.args

    messages.success(request, msg)

    if path:
        return redirect(path)
    else:
        return redirect('video:bookmark_list')


def bookmark_list(request):
    videos = Video.objects.all()
    context = {
        'videos': videos,
    }
    return render(request, 'video/bookmark_list.html', context)


def bookmark_detail(request, pk):
    video = Video.objects.get(pk=pk)
    # print(video.youtube_id)
    context = {
        'video': video,
    }
    return render(request, 'video/bookmark_detail.html', context)


def bookmark_delete(request, pk):
    video = Video.objects.get(pk=pk)
    video.delete()
    return redirect('video:bookmark_list')

djangogirls/video/views/search.py
from django.shortcuts import render
from video.apis.youtube import youtube_search

__all__ = ['search']


def search(request):
    context = {}
    keyword = request.GET.get('keyword')
    page_token = request.GET.get('page_token')
    if keyword:
        response = youtube_search(keyword, page_token)
        context['keyword'] = keyword
        context['response'] = response
    return render(request, 'video/search.html', context)

djangogirls/templates/video/bookmark_detail.html
{% extends 'common/base.html' %}

{% block content %}
<h2>{{ video.youtube_id}}</h2>

<iframe width="560" height="315" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allowfullscreen></iframe>
{% endblock%}

djangogirls/templates/video/bookmark_list.html
{% extends 'common/base.html' %}
{% block content%}
<div>BookMark List</div>


<ul>
    {% for video in videos %}
    <li>
        <a href="{% url 'video:bookmark_detail' pk=video.pk %}">
            <p><img src="{{ video.thumbnail }}"></p>
        </a>
        <p>title : {{ video.title }}</p>
        <p>desc : {{ video.description }}</p>
        <p>date : {{ video.published_date|date:"Y.m.d" }}</p>
        <a href="{% url 'video:bookmark_delete' pk=video.pk %}">
            <button type="submit">Delete</button>
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

djangogirls/templates/video/search.html
{% extends 'common/base.html' %}
{% load app_filters %}
{% load humanize %}

{% block content %}
<h5>"{{ keyword }}"로 검색 (총 {{ response.totalResults|intcomma }} 건의 영상검색)</h5>
<form>
    <label>검색어</label>
    <input type="text" name="keyword" placeholder={{ keyword }}>
    <button type="submit">검색</button>
</form>


<ul>
    {% for item in response.items %}
    <li>
        <p>게시일 : {{ item.snippet.publishedAt|string_to_date }}</p>
        <p>제목 : {{ item.snippet.title }}</p>
        <p><img src="{{ item.snippet.thumbnails.default.url }}"></p>
        <p>내용 : {{ item.snippet.description }}</p>
        <p>조회수 : {{ item.statistics.viewCount|intcomma }}</p>
        <p>좋아요수 : {{ item.statistics.likeCount|intcomma }}</p>
        <p>댓글수 : {{ item.statistics.commentCount|intcomma }}</p>

        {% if item.snippet.tags %}
        <p>태그목록 : {{ item.snippet.tags }}</p>
        {% else %}
        <p>태그목록 : 없음</p>
        {% endif %}

        <p>is_exist : {{ item.is_exist }}</p>
<!--#name이 key, value가 값으로 -->
        {% if item.is_exist %}
        <button>Already added</button>
        {% else %}
        <form action="{% url 'video:bookmark_add' %}" method="post">{% csrf_token %}
            <input type="hidden" name="kind" value="{{ item.kind }}">
            <input type="hidden" name="youtube_id" value="{{ item.id }}">
            <input type="hidden" name="title" value="{{ item.snippet.title }}">
            <input type="hidden" name="description" value="{{ item.snippet.description }}">
            <input type="hidden" name="published_date" value="{{ item.snippet.publishedAt }}">
            <input type="hidden" name="thumbnail" value="{{ item.snippet.thumbnails.default.url }}">
            <input type="hidden" name="path" value="{{ request.get_full_path }}">
            <button type="submit">Add Bookmark</button>
        </form>
        {% endif %}
    </li>
    {% endfor %}

    <div>
        {% if response.prevPageToken %}
        <a href="{% url 'video:search' %}?keyword={{ keyword }}&page_token={{ response.prevPageToken }}">이전페이지</a>
        {% endif %}

        {% if response.prevPageToken %}
        <a href="{% url 'video:search' %}?keyword={{ keyword }}">첫페이지</a>
        {% endif %}

        {% if response.nextPageToken %}
        <a href="{% url 'video:search' %}?keyword={{ keyword }}&page_token={{ response.nextPageToken }}">다음페이지</a>
        {% endif %}
    </div>
</ul>
{% endblock %}