youtube/django_app/video/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'search/$', views.search, name='search'),
    url(r'add_bookmark', views.add_bookmark, name='add_bookmark'),
    url(r'bookmark_list', views.bookmark_list, name='bookmark_list'),
]

youtube/django_app/youtube/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('video.urls', namespace='video')),
]

youtube/django_app/member/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager, User


# 기본 장고 유저(auth.User)의 Manager와 User를 상속받아 사용합니다
class YoutubeUserManager(UserManager):
    pass


class YoutubeUser(AbstractUser):
    nickname = models.CharField(max_length=24)

    class Meta:
        verbose_name = '사용자'
        verbose_name_plural = '사용자 목록'

    def __str__(self):
        return self.username

youtube/django_app/member/views.py
from django.shortcuts import render

# Create your views here.

youtube/django_app/video/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from googleapiclient.discovery import build
from .models import Video

DEVELOPER_KEY = "AIzaSyDqBzZV0nqWGKd7oGMR7e6ZsQ1KdWUA-dk"
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"


def youtube_search(keyword, page_token, max_results=10):
    youtube = build(
        YOUTUBE_API_SERVICE_NAME,
        YOUTUBE_API_VERSION,
        developerKey=DEVELOPER_KEY
    )

    search_response = youtube.search().list(
        q=keyword,
        part="id,snippet",
        maxResults=max_results,
        pageToken=page_token,
        ).execute()

    return search_response


def search(request):
    context = {}
    keyword = request.GET.get('keyword')
    page_token = request.GET.get('page_token')
    if keyword:
        response = youtube_search(keyword, page_token)
        context['keyword'] = keyword
        context['response'] = response
    return render(request, 'video/search.html', context)


def add_bookmark(request):
    if request.method == "POST":
        kind = request.POST.get('kind')
        youtube_id = request.POST.get('youtube_id')
        title = request.POST.get('title')
        description = request.POST.get('description')
        published_date = request.POST.get('published_date')
        thumbnail = request.POST.get('thumbnail')
        print(kind, youtube_id, title, description, published_date, thumbnail)
        # Video.objects.create(
        #     kind=kind,
        #     youtube_id=youtube_id,
        #     title=title,
        #     description=description,
        #     published_date=published_date,
        #     thumbnail=thumbnail,
        # )

        return HttpResponseRedirect('bookmark_list')
    else:
        return HttpResponse("nope")


def bookmark_list(request):
    bookmark_lists = Video.objects.all()
    context = {
        'bookmark_lists': bookmark_lists,
    }
    return render(request, 'video/bookmark_list.html', context)

youtube/django_app/templates/video/bookmark_list.html
<div>BookMark List</div>

<div>
    <ul>
        {% for video in bookmark_lists %}
        <div>{{ video.title }}</div>
        <div><img src="{{ video.thumbnail }}"></div>
        {% endfor %}
    </ul>
</div>

<a href="{% url 'video:search' %}">검색페이지</a>

youtube/django_app/templates/video/search.html
{% load app_filters %}
<form>
    <label>검색어</label>
    <input type="text" name="keyword" placeholder={{ keyword }}>
    <button type="submit">검색</button>
</form>


<button><a href="{% url 'video:bookmark_list' %}">Bookmark list보기</a></button>

<div>
    <ul>
        {% for item in response.items %}
        <li>
            <p>게시일 : {{ item.snippet.publishedAt|string_to_date }}</p>
            <p>제목 : {{ item.snippet.title }}</p>
            <p><img src="{{ item.snippet.thumbnails.default.url }}"></p>
            <p>내용 : {{ item.snippet.description }}</p>
        </li>


        <form action="{% url 'video:add_bookmark' %}" method="post">{% csrf_token %}
            <input type="hidden" name="kind" value={{ item.id.kind }}>
            <input type="hidden" name="youtube_id" value={{ item.id.videoId }}>
            <input type="hidden" name="title" value={{ item.snippet.title }}>
            <input type="hidden" name="description" value={{ item.snippet.description }}>
            <input type="hidden" name="published_date" value={{ item.snippet.publishedAt }}>
            <input type="hidden" name="thumbnail" value={{ item.snippet.thumbnails.default.url }}>
            <button>Bookmark</button>
        </form>
        {% endfor %}
        <div>
        {% if response.prevPageToken %}
            <a href="{% url 'video:search' %}?keyword={{ keyword }}&page_token={{ response.prevPageToken }}">이전페이지</a>
        {% endif %}

        {% if response.prevPageToken %}
            <a href="{% url 'video:search' %}?keyword={{ keyword }}">첫페이지</a>
        {% endif %}

        {% if response.nextPageToken %}
            <a href="{% url 'video:search' %}?keyword={{ keyword }}&page_token={{ response.nextPageToken }}">다음페이지</a>
        {% endif %}
        </div>
    </ul>

</div>